-- Seed test threat intelligence signals for development
-- Run this migration to populate the signals table with realistic test data

INSERT INTO signals (
  title, description, severity, category, source_name, source_url,
  cve_ids, industry, confidence_score, is_verified, tags, created_at, updated_at
) VALUES
  (
    'Critical: MOVEit Transfer RCE Vulnerability Exploited',
    'Threat actors are actively exploiting CVE-2024-5274 in Progress MOVEit Transfer. This zero-day vulnerability allows remote code execution without authentication.',
    'critical',
    'vulnerability',
    'BleepingComputer',
    'https://www.bleepingcomputer.com/moveit-transfer-rce',
    '["CVE-2024-5274"]',
    'Technology',
    0.98,
    true,
    '["RCE", "zero-day", "exploitation", "MFT"]',
    NOW(),
    NOW()
  ),
  (
    'High: LockBit 3.0 Ransomware Campaign Targeting Finance Sector',
    'LockBit 3.0 has launched a new ransomware campaign targeting financial institutions with focus on banking trojans and credential harvesting.',
    'high',
    'malware',
    'Krebs on Security',
    'https://krebsonsecurity.com/lockbit-3-campaign',
    '[]',
    'Financial Services',
    0.92,
    true,
    '["ransomware", "LockBit", "finance", "credential-theft"]',
    NOW(),
    NOW()
  ),
  (
    'High: Apache Log4j Exploitation in the Wild',
    'Continued exploitation of Log4j CVE-2021-44228 detected across multiple sectors. Attackers using it for initial access in multi-stage attacks.',
    'high',
    'vulnerability',
    'BleepingComputer',
    'https://www.bleepingcomputer.com/log4j-exploitation',
    '["CVE-2021-44228"]',
    'Multiple',
    0.95,
    true,
    '["log4j", "exploitation", "java", "widespread"]',
    NOW(),
    NOW()
  ),
  (
    'Medium: Phishing Campaign Using Lookalike Domains',
    'New phishing campaign detected using homograph attacks with Unicode characters to mimic popular SaaS platforms. 45% click rate reported.',
    'medium',
    'phishing',
    'Security Intelligence',
    'https://securityintel.example.com/phishing-unicode',
    '[]',
    'SaaS',
    0.87,
    true,
    '["phishing", "social-engineering", "unicode", "homograph"]',
    NOW(),
    NOW()
  ),
  (
    'High: Windows 0-Day Privilege Escalation Discovered',
    'A new Windows privilege escalation vulnerability affecting Windows 10/11 has been discovered. Remote attackers can escalate from user to SYSTEM.',
    'high',
    'vulnerability',
    'NVD',
    'https://nvd.nist.gov/vuln/detail/CVE-2024-1234',
    '["CVE-2024-1234"]',
    'Technology',
    0.99,
    true,
    '["windows", "privilege-escalation", "kernel", "critical"]',
    NOW(),
    NOW()
  ),
  (
    'Low: Suspicious DNS Activity in Ukraine',
    'Increased suspicious DNS queries detected in Ukrainian infrastructure. Pattern matches previous APT29 infrastructure reconnaissance.',
    'low',
    'suspicious-activity',
    'Threat Intel Feed',
    'https://threatfeed.example.com/ukraine-dns',
    '[]',
    'Government',
    0.72,
    false,
    '["apt29", "reconnaissance", "dns", "ukraine"]',
    NOW(),
    NOW()
  ),
  (
    'Medium: New Variant of Emotet Botnet Detected',
    'Security researchers have identified a new variant of the Emotet botnet with enhanced C&C communication obfuscation and anti-analysis capabilities.',
    'medium',
    'malware',
    'Malwarebytes',
    'https://malwarebytes.example.com/emotet-variant',
    '[]',
    'Multiple',
    0.88,
    true,
    '["emotet", "botnet", "c2", "obfuscation"]',
    NOW(),
    NOW()
  ),
  (
    'Critical: CISA Warns of Active Exploitation of Fortinet FortiOS Vulnerability',
    'CISA has added CVE-2023-27997 to its Known Exploited Vulnerabilities catalog. Multiple threat actors actively exploiting Fortinet FortiOS VPN devices.',
    'critical',
    'vulnerability',
    'CISA KEV',
    'https://www.cisa.gov/known-exploited-vulnerabilities',
    '["CVE-2023-27997"]',
    'Technology',
    0.99,
    true,
    '["fortinet", "vpn", "kev", "exploitation"]',
    NOW(),
    NOW()
  ),
  (
    'High: Supply Chain Attack via Compromised NPM Package',
    'Researchers discovered a malicious NPM package with 2.3M downloads that injects cryptocurrency mining code. Package was published by compromised maintainer.',
    'high',
    'supply-chain',
    'GitHub Security Advisory',
    'https://github.com/advisories/npm-malicious',
    '[]',
    'Software Development',
    0.96,
    true,
    '["supply-chain", "npm", "malware", "cryptomining"]',
    NOW(),
    NOW()
  ),
  (
    'Medium: Increased DDoS Activity Against Government Websites',
    'Multiple government websites across NATO countries experiencing coordinated DDoS attacks. Attack pattern matches Russian-affiliated threat group Killnet.',
    'medium',
    'ddos',
    'Cloudflare Threat Report',
    'https://cloudflare.com/ddos-report',
    '[]',
    'Government',
    0.85,
    true,
    '["ddos", "killnet", "nato", "government"]',
    NOW(),
    NOW()
  );
